<?php

use Hyva\Theme\Model\ViewModelRegistry;
use InPost\InPostPay\ViewModel\Widget;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Widget $widgetViewModel */
/** @var Escaper $escaper */

$widgetViewModel = $viewModels->require(Widget::class);

$widgetViewModel = $block->getData('widget_view_model');
if (!$widgetViewModel->isEnabled() || !$widgetViewModel->isEnabledOnCart()) {
    return;
}

$bindingPlace = $block->getBindingPlace();
$layoutConfig = $widgetViewModel->getLayoutConfig();
$widgetWrapperClass = "inpay-widget-wrapper";
?>

<?= $block->getChildBlock('inpost.hyva.widget.cart.script')->setData('isCart', true)->toHtml() ?>

<div x-data="initializeInpostPay_<?= $escaper->escapeJs($bindingPlace) ?>()"
     @private-content-loaded.window="receiveCustomerData($event.detail.data)"
     @cart-is-loading.window="receiveCartUpdate($event.detail)"
     @cart-item-removed.window="receiveCartRemove()"
     class="<?= $escaper->escapeHtmlAttr($widgetWrapperClass) . ' ' . $escaper->escapeHtmlAttr($bindingPlace) ?>">
    <inpost-izi-button
        binding_place="<?= $escaper->escapeHtmlAttr($bindingPlace) ?>"
        variation="<?= $escaper->escapeHtmlAttr($layoutConfig) ?>"
    ></inpost-izi-button>
</div>
