<?php

use Hyva\Theme\Model\ViewModelRegistry;
use InPost\InPostPay\ViewModel\Widget;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var Widget $widgetViewModel */

$widgetViewModel = $viewModels->require(Widget::class);

$widgetViewModel = $block->getData('widget_view_model');
if (!$widgetViewModel->isEnabled()
    || !$widgetViewModel->isInPostPayOrder()
    || !$widgetViewModel->isEnabledOnSuccessPage()) {
    return;
}

$wrapperClass = "inpay-widget-wrapper";
$bindingPlace = $block->getBindingPlace();
?>

<?= $block->getChildBlock('inpost.hyva.widget.success.page.script')->toHtml() ?>

<div x-data="initializeInpostPay_<?= $escaper->escapeJs($bindingPlace) ?>()"
     @private-content-loaded.window="receiveCustomerData($event.detail.data)"
     class="container <?= $escaper->escapeHtmlAttr($wrapperClass) . ' ' . $escaper->escapeHtmlAttr($bindingPlace) ?>">
    <inpost-thank-you />
</div>
